//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.01 at 05:44:14 PM EEST 
//


package lt.viko.eif.dborkovskij.soap.localhost.cinema.theaterroom;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the localhost.cinema.theaterroom package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: localhost.cinema.theaterroom
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InsertTheaterRoomRequest }
     * 
     */
    public InsertTheaterRoomRequest createInsertTheaterRoomRequest() {
        return new InsertTheaterRoomRequest();
    }

    /**
     * Create an instance of {@link TheaterRoom }
     * 
     */
    public TheaterRoom createTheaterRoom() {
        return new TheaterRoom();
    }

    /**
     * Create an instance of {@link GetTheaterRoomResponse }
     * 
     */
    public GetTheaterRoomResponse createGetTheaterRoomResponse() {
        return new GetTheaterRoomResponse();
    }

    /**
     * Create an instance of {@link GetTheaterRoomsRequest }
     * 
     */
    public GetTheaterRoomsRequest createGetTheaterRoomsRequest() {
        return new GetTheaterRoomsRequest();
    }

    /**
     * Create an instance of {@link GetTheaterRoomsResponse }
     * 
     */
    public GetTheaterRoomsResponse createGetTheaterRoomsResponse() {
        return new GetTheaterRoomsResponse();
    }

    /**
     * Create an instance of {@link InsertTheaterRoomResponse }
     * 
     */
    public InsertTheaterRoomResponse createInsertTheaterRoomResponse() {
        return new InsertTheaterRoomResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link DeleteTheaterRoomRequest }
     * 
     */
    public DeleteTheaterRoomRequest createDeleteTheaterRoomRequest() {
        return new DeleteTheaterRoomRequest();
    }

    /**
     * Create an instance of {@link DeleteTheaterRoomResponse }
     * 
     */
    public DeleteTheaterRoomResponse createDeleteTheaterRoomResponse() {
        return new DeleteTheaterRoomResponse();
    }

    /**
     * Create an instance of {@link UpdateTheaterRoomResponse }
     * 
     */
    public UpdateTheaterRoomResponse createUpdateTheaterRoomResponse() {
        return new UpdateTheaterRoomResponse();
    }

    /**
     * Create an instance of {@link GetTheaterRoomRequest }
     * 
     */
    public GetTheaterRoomRequest createGetTheaterRoomRequest() {
        return new GetTheaterRoomRequest();
    }

    /**
     * Create an instance of {@link UpdateTheaterRoomRequest }
     * 
     */
    public UpdateTheaterRoomRequest createUpdateTheaterRoomRequest() {
        return new UpdateTheaterRoomRequest();
    }

}
